### ISSUE TITLE
Should we consider turning `fct` into a map as opposed to array

### ISSUE THREAD

**Issue by Gozala** [ucan-wg/spec#134] opened 2022-11-27 18:22 UTC
On multiple occasions I wished and sometimes mistakenly assumed that `fct` is map and I could demand specific field for certain purposes. With array we have to deal with possible plurality of values, which has pros and cons. We are also considering turning [`att` into map in 0.10](https://github.com/ucan-wg/spec/pull/132) perhaps it's a good idea to consider the same here.

It is worth pointing out that plurality could still be accomplished simply by using CID of the data as key of the map, while doing the reverse is not really possible. For example we wanted to embed mapping from DIDs to Public keys (signed by the root key) to reduce IO involved with resolution, however using arrays introduces possibility that we may have multiple keys for the same DID which in turn introduces ambiguity which one is used in given context.

**Comment by expede** [comment] 2022-11-27 19:23
I'm certainly not against this change. I guess the problem is if I have two APIs that expect different data inside the same named `challenge` key. But they `SHOULD` either prefix them (`{"foo/challenge": ..., "bar/challenge": ...}`) or nest them (`{challenges: {foo: ..., bar: ...}`).

For consistency with the rest of our patterns, I think the ad hoc prefixing is probably the right call 👍

**Comment by expede** [comment] 2022-11-27 19:24
I'm strongly in favour. Marked for inclusion in v0.10

**Comment by expede** [comment] 2023-07-12 02:05
Closed by #132

**Closed by expede** 2023-07-12 02:05 UTC
